stop-service-mysql:
	docker-compose -p cdt down
start-service-mysql:
	docker-compose -p cdt down && docker-compose -p cdt up -d
restart-service-mysql:
	docker-compose -p cdt restart
see-docker-container-list:
	docker-compose -p cdt ps -a
